### ISSUE TITLE
[facial_expression/miraikan_demo] ペッパーの発話の前にこちさんをちらっと見る動作の追加についてのご相談

### ISSUE THREAD

**Issue by kochigami** [MiyabiTane/Deco_with_robot#4]
@a-ichikuraさんが作ってくださった発話と動作のファイルに対して、
いくつかプルリクエストを送ったのですが、眉毛のタイミングに影響ありそうなものが１つあるので、issueを立てました。

https://github.com/a-ichikura/Deco_with_robot/pull/3 の`look_at_kochisan_mini`関数です。

@a-ichikuraさんのプログラムを実行してみた時に、
ロボットの発話に「コチさん」か「わたしたち」が含まれる時、
私の方をちらっと見てくれた方が話しやすいと思ったので、

発話文に、「コチさん」か「わたしたち」が含まれる時、
関数の中身（例：episode_11）を
１．私の方をちらっと見る（2.5秒間の動作）（追加部分）
2.5秒の根拠：https://github.com/a-ichikura/Deco_with_robot/pull/3/files#diff-bed4d4b52e158cea0f36a48e233535f81ecfc885c5b4fee18e18d65ba080231bR124
２．ペッパーが発話を始める

というようにしてあります。

眉毛のタイミングがずれて大変になってしまうようであれば消そうと思います。
ご都合のよろしい時に、ご確認をお願いします。

**Comment by a-ichikura** [comment]
一応、
https://github.com/MiyabiTane/Deco_with_robot/pull/6#issue-1321694275
上の```look_at_kochisan_mini```も含めた状態でのPRを送りました。

**Comment by MiyabiTane** [comment]
眉毛デバイスに関して、左右のタイミングを合わせるために仕様を変更していて、どのみち全てのタイミングを合わせ直す必要があったため、今日中であれば気にせず変えていただいて問題ないです

**Comment by kochigami** [comment]
お客さんから見て自然か、という所まできちんと確認しきれておらず・・・
もし動きが遅いなど感じることがあったら、遠慮なく直して/ 指摘してくださるとありがたいです！
お手数をお掛けしますが、よろしくお願いいたします。

**Comment by MiyabiTane** [comment]
皆様実験お疲れ様でした！！
`look_at_kochisan`の動き、とても役に立ちました。そして可愛かったです！

issueを閉じます
