### ISSUE TITLE
@kochigami の残り作業について

### ISSUE THREAD

**Issue by kochigami** [MiyabiTane/Deco_with_robot#5]
7/29（金）までにペッパーの発話・動作の部分の修正を終わらせるという約束だったと思うのですが、
終わらなかったので（すみません・・・）、
私が今後作業したい内容を書かせていただきます。できれば今日中に終わらせたいと思います。

ーーー
https://github.com/MiyabiTane/Deco_with_robot/issues/4 の内容は眉毛のタイミングに影響を与えそうなのですが、
以下の今後行う予定の作業は、眉毛のタイミングには影響がないと思います。

- 頭を上げすぎないように、頭のstiffnessが0になっている所の修正。例えば、https://github.com/a-ichikura/Deco_with_robot/pull/3/files#diff-5f3c0c7fce5fc3eb140d22d8b2ce3d70ac024f6097a958e61392261f9b9fc8abR311
 0だと、突然胴体の動きで、首がバタン！と倒れることがあるので，stiffness 0.5くらいで動きが押さえ目かつ首もバタン！とならないいい感じになってくれないかを確認する => https://github.com/MiyabiTane/Deco_with_robot/pull/7

- ペッパーが喋っていない時に両手をパタっとする控え目な動き追加（ペッパーが喋っていないときの棒立ちが気になってしまって・・・落ち着きない印象を与えるようだったらやめる）

- https://github.com/MiyabiTane/Deco_with_robot/issues/4 の `look_at_kochisan_mini` 関数に関して、横をちらっと向く時に、瞬きをいれてみる => https://github.com/MiyabiTane/Deco_with_robot/pull/9

- 音量調整，AutonomousLifeをdisableする設定は、現状Choregrapheで行うと聞いたので、
  念の為、Choregrapheがなくても設定できるよう、Pythonの別プログラムの追加 => https://github.com/MiyabiTane/Deco_with_robot/pull/8

**Comment by kochigami** [comment]
> ペッパーが喋っていない時に両手をパタっとする控え目な動き追加（ペッパーが喋っていないときの棒立ちが気になってしまって・・・落ち着きない印象を与えるようだったらやめる）

以外のプルリクエストをお送りしました。
パタッとする動きについては，rospyのspin onceをどうやって書くのかパッとは分からず・・・
今日は諦めて，また後日やってみようと思います．
（多分眉毛のタイミングにご迷惑を掛けることはないと思います，もしご迷惑を掛けることになったらやめます！）

たくさんプルリクエストを送ってしまいすみません、ご確認をよろしくお願いいたします。

**Comment by MiyabiTane** [comment]
こちら全てのPRに対応済みなのでissueを閉じさせて頂きます
